# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfc75fb811b354128d6534d63e8062dbaeedd83459dfc1c875d1af5b2a38a107c5fb97e98ee7e176c34dae04bee55f44da40bf7d429ee65b5b516aba153e2f19

test:
  secret_key_base: 89975c061fc22ae74cf23657f8b89d1e35de776e83f2acbbd6bae11097c4cbf12badc0cb1acb6fb9a61ebdf79ff64122a9db6628b5fc1729754c7e6d1a1130ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
